import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600' as const,
    color: '#333',
  },
  closeButton: {
    padding: 5,
  },
  productInfo: {
    marginBottom: 25,
  },
  productName: {
    fontSize: 16,
    fontWeight: '500' as const,
    color: '#333',
    marginBottom: 8,
  },
  variantInfo: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  stockInfo: {
    fontSize: 12,
    color: '#704F38',
    fontWeight: '500' as const,
  },
  quantitySection: {
    marginBottom: 25,
  },
  quantityLabel: {
    fontSize: 16,
    fontWeight: '500' as const,
    color: '#333',
    marginBottom: 15,
  },
  quantityControls: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  quantityButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    borderWidth: 1,
    borderColor: '#704F38',
  },
  quantityButtonDisabled: {
    backgroundColor: '#F9F9F9',
    borderColor: '#E5E5E5',
  },
  quantityDisplay: {
    marginHorizontal: 30,
    minWidth: 50,
    alignItems: 'center' as const,
  },
  quantityText: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: '#333',
  },
  priceSection: {
    marginBottom: 30,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#E5E5E5',
  },
  priceRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: 8,
  },
  priceLabel: {
    fontSize: 14,
    color: '#666',
  },
  priceValue: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500' as const,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#333',
  },
  totalValue: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#704F38',
  },
  actionButtons: {
    flexDirection: 'row' as const,
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    height: 50,
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '500' as const,
    color: '#666',
  },
  addToCartButton: {
    flex: 2,
    height: 50,
    backgroundColor: '#704F38',
    borderRadius: 8,
    flexDirection: 'row' as const,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  addToCartButtonDisabled: {
    backgroundColor: '#CCCCCC',
  },
  addToCartButtonText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  messageContainer: {
    marginVertical: 12,
    paddingHorizontal: 16,
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FFF5F5',
    borderLeftWidth: 4,
    borderLeftColor: '#FF6B6B',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  warningContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FFFBF0',
    borderLeftWidth: 4,
    borderLeftColor: '#FFA500',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  errorText: {
    flex: 1,
    marginLeft: 8,
    fontSize: 14,
    color: '#D32F2F',
    lineHeight: 20,
  },
  warningText: {
    flex: 1,
    marginLeft: 8,
    fontSize: 14,
    color: '#F57C00',
    lineHeight: 20,
  },
});