import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#666',
    fontFamily: 'Poppins-Regular',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    paddingHorizontal: 32,
  },
  errorTitle: {
    fontSize: 20,
    fontFamily: 'Poppins-SemiBold',
    color: '#333',
    marginTop: 16,
  },
  errorSubtitle: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginTop: 8,
    fontFamily: 'Poppins-Regular',
  },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 24,
    borderWidth: 1,
    borderColor: '#704F38',
  },
  retryButtonText: {
    fontSize: 16,
    color: '#704F38',
    fontFamily: 'Poppins-Medium',
    marginLeft: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
  },
  headerBackButton: {
    padding: 8,
    marginRight: 8,
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: 'Poppins-SemiBold',
    color: '#333',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#666',
    fontFamily: 'Poppins-Regular',
    marginTop: 2,
  },
  scrollView: {
    flex: 1,
  },
  reviewsList: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  reviewCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
  },
  reviewHeaderLeft: {
    flex: 1,
  },
  reviewTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  reviewOrderId: {
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
    color: '#333',
    marginRight: 12,
  },
  reviewRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewRatingText: {
    fontSize: 14,
    color: '#666',
    fontFamily: 'Poppins-Medium',
    marginLeft: 6,
  },
  reviewDateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewDate: {
    fontSize: 12,
    color: '#666',
    fontFamily: 'Poppins-Regular',
    marginLeft: 4,
  },
  reviewHeaderRight: {
    alignItems: 'flex-end',
  },
  productCount: {
    fontSize: 12,
    color: '#666',
    fontFamily: 'Poppins-Regular',
    marginBottom: 4,
  },
  reviewContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  overallCommentSection: {
    marginBottom: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
    color: '#333',
    marginLeft: 6,
  },
  commentText: {
    fontSize: 14,
    color: '#666',
    fontFamily: 'Poppins-Regular',
    lineHeight: 20,
    fontStyle: 'italic',
  },
  productReviewsSection: {
    marginBottom: 16,
  },
  productReviewItem: {
    backgroundColor: '#F8F9FA',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  productReviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  productReviewTitle: {
    fontSize: 13,
    fontFamily: 'Poppins-Medium',
    color: '#333',
  },
  productVariant: {
    fontSize: 12,
    color: '#666',
    fontFamily: 'Poppins-Regular',
  },
  productReviewRating: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  productRatingText: {
    fontSize: 12,
    color: '#666',
    fontFamily: 'Poppins-Medium',
    marginLeft: 4,
  },
  productCommentText: {
    fontSize: 12,
    color: '#666',
    fontFamily: 'Poppins-Regular',
    fontStyle: 'italic',
    lineHeight: 16,
  },
  additionalRatingsSection: {
    marginBottom: 16,
  },
  additionalRatingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  additionalRatingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  additionalRatingLabel: {
    fontSize: 13,
    color: '#333',
    fontFamily: 'Poppins-Regular',
    marginLeft: 6,
  },
  additionalRatingValue: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  additionalRatingText: {
    fontSize: 12,
    color: '#666',
    fontFamily: 'Poppins-Medium',
    marginLeft: 4,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#704F38',
    flex: 0.48,
    justifyContent: 'center',
  },
  editButtonText: {
    fontSize: 14,
    color: '#704F38',
    fontFamily: 'Poppins-Medium',
    marginLeft: 4,
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF5F5',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#DC3545',
    flex: 0.48,
    justifyContent: 'center',
  },
  deleteButtonText: {
    fontSize: 14,
    color: '#DC3545',
    fontFamily: 'Poppins-Medium',
    marginLeft: 4,
  },
  starContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  emptyTitle: {
    fontSize: 20,
    fontFamily: 'Poppins-SemiBold',
    color: '#333',
    marginTop: 16,
  },
  emptySubtitle: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginTop: 8,
    fontFamily: 'Poppins-Regular',
  },
  bottomSpacing: {
    height: 32,
  },
});